[36m--[0m Using CATKIN_DEVEL_PREFIX: /home/xavier/catkin_ws/devel/.private/pitakuru
[36m--[0m Using CMAKE_PREFIX_PATH: /home/xavier/catkin_ws/devel;/opt/ros/melodic
[36m--[0m This workspace overlays: /home/xavier/catkin_ws/devel;/opt/ros/melodic
[36m--[0m Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2")
[36m--[0m Using PYTHON_EXECUTABLE: /usr/bin/python2
[36m--[0m Using Debian Python package layout
[36m--[0m Using empy: /usr/bin/empy
[36m--[0m Using CATKIN_ENABLE_TESTING: ON
[36m--[0m Call enable_testing()
[36m--[0m Using CATKIN_TEST_RESULTS_DIR: /home/xavier/catkin_ws/build/pitakuru/test_results
[36m--[0m Found gtest sources under '/usr/src/googletest': gtests will be built
[36m--[0m Found gmock sources under '/usr/src/googletest': gmock will be built
[36m--[0m Found PythonInterp: /usr/bin/python2 (found version "2.7.17")
[36m--[0m Using Python nosetests: /usr/bin/nosetests-2.7
[36m--[0m catkin 0.7.29
[36m--[0m BUILD_SHARED_LIBS is on
[36m--[0m Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
[36m--[0m Generating .msg files for action pitakuru/Sound /home/xavier/catkin_ws/src/pitakuru/action/Sound.action
/opt/ros/melodic/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <class 'genmsg.base.InvalidMsgSpec'>: /home/xavier/catkin_ws/src/pitakuru/msg/peoples.msg: people[] is not a legal message field name
Traceback (most recent call last):
  File "/usr/bin/empy", line 3302, in <module>
    if __name__ == '__main__': main()
  File "/usr/bin/empy", line 3300, in main
    invoke(sys.argv[1:])
  File "/usr/bin/empy", line 3283, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/bin/empy", line 2295, in wrap
    self.fail(e)
  File "/usr/bin/empy", line 2284, in wrap
    callable(*args)
  File "/usr/bin/empy", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/bin/empy", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/bin/empy", line 2421, in parse
    token.run(self, locals)
  File "/usr/bin/empy", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/bin/empy", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "/usr/bin/empy", line 42, in _exec
    exec("""exec code in globals""")
  File "<string>", line 1, in <module>
  File "<string>", line 38, in <module>
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/deps.py", line 45, in find_msg_dependencies_with_type
    spec = genmsg.msg_loader.load_msg_from_file(msg_context, msg_file, full_type_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 289, in load_msg_from_file
    raise InvalidMsgSpec('%s: %s'%(file_path, e))
genmsg.base.InvalidMsgSpec: /home/xavier/catkin_ws/src/pitakuru/msg/peoples.msg: people[] is not a legal message field name
[31m[1mCMake Error[0m at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/home/xavier/catkin_ws/build/pitakuru/catkin_generated/env_cached.sh
  "/usr/bin/python2" "/usr/bin/empy" "--raw-errors" "-F"
  "/home/xavier/catkin_ws/build/pitakuru/cmake/pitakuru-genmsg-context.py"
  "-o" "/home/xavier/catkin_ws/build/pitakuru/cmake/pitakuru-genmsg.cmake"
  "/opt/ros/melodic/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
[36mCall Stack (most recent call first):[0m
  /opt/ros/melodic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  CMakeLists.txt:77 (generate_messages)


[36m--[0m Configuring incomplete, errors occurred!
See also "/home/xavier/catkin_ws/build/pitakuru/CMakeFiles/CMakeOutput.log".
See also "/home/xavier/catkin_ws/build/pitakuru/CMakeFiles/CMakeError.log".
Makefile:992: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
